routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PortadaController@index');

Route::get('/gravatar', 'GravatarController@gravatar');



Route::resource('service','ServiceController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Inicia rutas para perfil de usuario */
Route::get('profile/create', 'ProfileController@create')->name('profile.create')->middleware('auth');
Route::post('profile', 'ProfileController@store')->name('profile.store')->middleware('auth');
Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit')->middleware('auth');
Route::put('profile/update', 'ProfileController@update')->name('profile.update')->middleware('auth');
Route::get('profile/{profile}', 'ProfileController@show')->name('profile.show')->middleware('auth');

/* == Finaliza rutas para perfil de usuario == */

/* Inicia ruta para eliminar usuario */
Route::delete('user/delete', 'ProfileController@destroy')->name('user.destroy')->middleware('auth');
/* == Finaliza ruta para eliminar usuario == */


/* Inicia rutas para posts y comentarios */
Route::post('post/store', 'PostController@store')->name('post.store')->middleware('auth');
Route::post('comment/store', 'CommentController@store')->name('comment.store')->middleware('auth');
/* == Finaliza ruta para posts y comentarios == */

/* Inicia rutas para peticion de servicios */
Route::post('purchase/store', 'PurchaseController@store')->name('purchase.store')->middleware('auth');
/* == Finaliza ruta para peticion de servicios == */

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'profile_id', 'title', 'description', 'price', 'picture_path'
    ];

    /**
     * Get the profile for the service
     */
    public function profile()
    {
        return $this->belongsTo('App\Profile');
    }

    /**
     * Set the scope search
     */
    public function scopeSearch($query,$search){
        if($search){
            return $query->where  ('title','LIKE',"%$search%")
                         ->orWhere('description','LIKE',"%$search%");
        }
    }

    /**
     * Get the comments for the blog post.
     */
    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    /**
     * Get the purchases for the service
     */
    public function purchases()
    {
        return $this->hasMany('App\Purchase');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use App\Profile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $profile = Profile::where("user_id", "=", \Auth::user()->id)->first();
        $search = $request->get('buscar');
        if($profile == null) {
            $user = \Auth::user();
            return redirect('profile/create')->with('message', 'Primero debe registrar su perfil');
        }
        $services = Service::where("profile_id", "=", $profile->id)->search($search)->paginate(3);

        return view('services.index', [
            "services" => $services,
            "busqueda" => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fields = [
            'title'=> 'required|string|max:100',
            'description'=> 'string',
            'price'=> 'required|regex:/^[0-9]+(\.[0-9]{1,3})?$/',
            'picture_path'=>'max:10000|mimes:jpeg,png,jpg'
        ];
        $message = ["required"=>' :attribute es requerido' ];

        $this->validate($request, $fields, $message);
        // $serviceData=request()->all();

        $serviceData = request()->except('_token');
        $profile = Profile::where("user_id", "=", \Auth::user()->id)->first();
        $serviceData['profile_id'] = $profile->id;

        if($request->hasFile('picture_path')){
            $serviceData['picture_path'] = $request->file('picture_path')->store('uploads','public');
        }


        Service::insert( $serviceData);
        //return response()->json($daserviceData
        return redirect('service')->with('message','Servicio agregado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        return view('services.show', compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        return view ('services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        $fields = [
            'title'=> 'required|string|max:100',
            'description'=> 'string',
            'price'=> 'required|regex:/^[0-9]+(\.[0-9]{1,3})?$/',
            'picture_path'=>'max:10000|mimes:jpeg,png,jpg'
        ];

        if($request->hasFile('picture_path')){

            $fields += ['picture_path'=>'max:10000|mimes:jpeg,png,jpg'];

        }

        $message = ["required"=>' :attribute es requerido' ];

        $this->validate($request, $fields, $message);

        $dataService = request()->except(['_token','_method']);


        if($request->hasFile('picture_path')){

            Storage::delete('public/'.$service->picture_path);

            $service->picture_path = $request->file('picture_path')->store('uploads','public');

        }

        $service->update($dataService);

        return redirect('service')->with('message','Información modificada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        if(Storage::delete('public/'.$service->picture_path)){
            $service->delete();
        }
        return redirect('service')->with('message','Servicio eliminado');
    }
}

resources/views/services/create.blade.php
@extends('adminlte::page')

@section('title', 'Registrando informacion')

@section('content_header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Crear Servicio</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="{{ route('service.index') }}">Servicio</a>
                        </li>
                        <li class="breadcrumb-item active">
                            Crear Servicio
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
@stop

@section('content')
<div class="container">
    @if(Session::has('Message'))
    <div class="alert alert-success" role="alert">
        {{Session::get('Message')}}
    </div>
    @endif
</div>


<section class="content">
</section>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Ficha del Servicio</h3>
                </div>
                <form action="{{ route('service.store') }}" role="form" method="post" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="card-body">
                        @include('services.form')
                    </div>
                    <div class="card-footer">
                        <div class="row justify-content-between">
                            <input type="submit" class="btn btn-primary" value="Agregar">

                            <a class="btn btn-outline-secondary" href="{{route('service.index')}}">Regresar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/services/edit.blade.php
@extends('adminlte::page')

@section('title', 'Cambio de informacion')

@section('content_header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Editar Servicio</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="{{ route('service.index') }}">Servicio</a>
                        </li>
                        <li class="breadcrumb-item active">
                            Editar Servicio
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
@stop

@section('content')
<section class="content">
</section>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Ficha del Servicio</h3>
                </div>
                <form action="{{ route('service.update', $service) }}" method="post" enctype="multipart/form-data">
                    {{csrf_field()}}
                    {{method_field('PATCH')}}
                    <div class="card-body">
                        @include('services.form')
                    </div>
                    <div class="card-footer">
                        <div class="row justify-content-between">
                            <input type="submit" class="btn btn-primary" value="Modificar">

                            <a class="btn btn-outline-secondary" href="{{route('service.index')}}">Regresar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/services/form.blade.php
<!-- Title -->
<div class="form-group">
    <label for="title" class="control-label">{{'Título'}}</label>
    <input
        type="text"
        class="form-control {{$errors->has('title')?'is-invalid':''}}"
        name="title"
        id="title"
        value="{{isset($service->title)?$service->title:old('title')}}">
        {!! $errors->first('title','<div class="alert alert-danger alert-dismissible">:message</div>')!!}
</div>


<!-- Description -->
<div class="form-group">
    <label for="description" class="control-label">{{'Descripción'}}</label>
    <textarea
        class="form-control"
        name="description"
        id="description"
        rows="3">{{ isset($service->description)?$service->description:old('description') }}</textarea>
</div>


<!-- Price -->
<div class="form-group">
    <label for="price" class="control-label">{{'Precio'}}</label>
    <input
        type="double"
        class="form-control {{$errors->has('price')?'is-invalid':''}}"
        name="price"
        id="price"
        value="{{isset($service->price)?$service->price:old('price')}}">
        {!! $errors->first('price','<div class="invalid-feedback">:message</div>')!!}
</div>


<!-- Picture -->
<div class="form-group justify-content-around">
    <label for="picture_path" class="control-label">{{'Imagen'}}</label>
    <div class="input-group">
        <div class="custom-file">
            <input
                type="file"
                class="custom-file-input"
                name="picture_path"
                id="picture_path">
        </div>
        <label class="custom-file-label" for="picture_path"></label>
    </div>
</div>

resources/views/services/index.blade.php
@extends('adminlte::page')

@section('title', 'Servicios')

@section('content_header')

    <div class="col-sm-13">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">
                <a href="{{ route('home') }}">Home</a>
            </li>
            <li class="breadcrumb-item active">
                Agregar Servicios
            </li>
        </ol>
    </div>


    <h1 class="m-0 text-dark">Administrar</h1>
    @if($busqueda)
        <h5 class="m-0 text-dark">Buscando: "{{$busqueda}}"</h5>
    @endif

@stop

@section('content')



<div class="container">
    @if(Session::has('message'))
    <div class="alert alert-success" role="alert">
        {{Session::get('message')}}
    </div>
    @endif
</div>


<div class="col-sm-13">
    <ol class="btn btn-success float-sm-left">
    <a href="{{ route('service.create') }}" class="btn btn-success -item">Agregar Servicio <i class="fas fa-plus"></i></a>
    </ol>
    </div>
    <br/>
    <br/>

    <table class="table table-bordered table-striped dataTable table-hover text-center" >

        <thead class="thead-light">
            <tr>
                <th><i class="fas fa-clipboard-check"></i></th>
                <th>Foto  <i class="fas fa-camera"></i></th>
                <th>Titulo  <i class="fas fa-tools"></i></th>
                <th>Precio(soles)  <i class="fas fa-hand-holding-usd"></i></th>
                <th>Descripción  <i class="fas fa-id-card"></i></th>
                <th>Acciones  <i class="fas fa-mouse"></i></th>
            </tr>

        </thead>

        <tbody>
            @foreach($services as $service)
            <tr>


                <td>{{$loop->iteration}}</td>

                <td>
                    <img src="{{asset('storage').'/'.$service->picture_path}}" class="img-thumbnail img-fluid" alt="" width="200">

                </td>
                <td>{{$service->title}}</td>
                <td>{{$service->price}}</td>
                <td>{{$service->description}}</td>
                <td>

                    <a class="btn btn-warning" href="{{ route('service.edit', $service) }}">Editar
                    </a>
                    <a class="btn btn-info" href="{{ route('service.show', $service) }}">Ver
                    </a>
                    <form method="post" action="{{ route('service.destroy', $service) }}" style="display:inline">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger" type="submit" onclick="return confirm('¿Borrar?');">Borrar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>

    </table>
    {{$services->links()}}

</div>
@stop

resources/views/services/show.blade.php
@extends('adminlte::page')
@section('title', 'Service Profile')

@section('content_header')
    <h1 class="m-0 text-dark">Perfil del Servicio</h1>
@stop

@section('content')

    <div class="card card-solid">
        <div class="card-body">
            <div class ="row">
                <div class = "col-12 col-sm-6">
                    <h3></h3>
                    <div class="col-12">
                        <img src="{{asset('storage').'/'.$service->picture_path}}" class="product-image" alt="Product Image">
                    </div>
                </div>


                <div class="col-12 col-sm-6">
                    <h1 class="my-3">{{$service->title}}</h1>
                    <h3> Descripcion del servicio </h3>
                    <p> {{$service->description}}</p>
                    <h3 class="my-3">Ofertante</h3>

                    <div class = "col-md-7">
                        <div class = "card card-dark">
                            <div class = "card-body box-profile">
                                <div class = "text-center">
                                    <img class="profile-user-img img-fluid img-circle" src="{{ Gravatar::get($service->profile->user->email)}}" alt="User profile picture">
                                </div>
                                <h3 class = "profile-username text-center"> {{ $service->profile->firstname ?? '' }} {{ $service->profile->lastname ?? '' }}   </h3>
                                <p class="text-muted text-center">{{ $service->profile->profession ?? '' }}</p>
                                <ul class="list-group list-group-unbordered mb-3">
                                    <li class="list-group-item">
                                        <b>Puntuacion</b> <a class="float-right">1,322</a>
                                    </li>
                                    <li class="list-group-item">
                                        <b>Seguidores</b> <a class="float-right">543</a>
                                    </li>
                                    <li class="list-group-item">
                                        <b>Total servicios</b> <a class="float-right">20</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <h3>Precio</h3>
                    <div class="bg-green py-2 px-3 mt-4">
                        <h2 class="mb-0">
                            S/ {{$service->price}}
                        </h2>
                    </div>
                    <div class="mt-4">
                        <div class="btn btn-primary btn-lg btn-flat">
                            <i class="fas fa-cart-plus fa-lg mr-2"></i>
                            <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#exampleModalCenter">Adquirir Servicio</button>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Petición de servicio</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <form class="form-horizontal" action="{{ route('purchase.store') }}" method="post">
                                    {{csrf_field()}}
                                    <div class="form-group">
                                        <input type="hidden" name="service_id" id="" value="{{ $service->id }}">
                                        <input type="hidden" name="profile_id" id="" value="{{ \Auth::user()->profile->id }}">
                                        <label>Fecha y hora de atención deseada</label>
                                        <input type="datetime-local" name="due_date" max="3000-12-31"
                                                min="1000-01-01" class="form-control">
                                    </div>
                                    <i class="fas fa-cart-plus fa-lg mr-2"></i>
                                    <button class="btn btn-primary" type="submit">Adquirir Servicio</button>
                                </form>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- Fin modal -->
                    </div>
                </div>
                <div class="row mt-4">
                    <nav class="w-100">
                        <div class="nav nav-tabs" id="product-tab" role="tablist">
                            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" role="tab" aria-controls="product-desc" aria-selected="true" href="#">Comentarios</a>
                        </div>
                    </nav>
                    <div class="col-md-12 p-3" id="nav-tabContent">
                        <div class="card">
                            <div class="card-body">
                                <form class="form-horizontal" action="{{ route('post.store') }}" method="post">
                                    {{csrf_field()}}
                                    <div class="input-group input-group-sm mb-0">
                                        <input class="form-control form-control-sm" type="text" name="body" id="" placeholder="Consultanos aquí...">
                                        <input type="hidden" name="service_id" id="" value="{{ $service->id }}">
                                        <input type="hidden" name="profile_id" id="" value="{{ \Auth::user()->profile->id }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="submit">Enviar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="tab-pane fade show active" role="tabpanel">
                            @include('posts.index')
                        </div>
                    </div>
                </div>
            </div>
        </div>
@stop